name: Update version on PR merge

on: [ push ]

jobs:

  update_latest_version:
    runs-on: ubuntu-latest
    permissions:
      issues: write 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
      - name: Display SemVer
        run: |
          echo "SemVer: $GITVERSION_SEMVER"
          
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3 
        with:
          token: ${{ secrets.GITHUB_TOKEN }}    
        
      - name: Create new version using REST API
        run: |
          curl \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GIST_PAT }}" \
          https://api.github.com/gists/b20fe2465ce76776e0ae632095d9d7c7 \
          -d '{"description":"v${{ steps.gitversion.outputs.fullSemVer }}","files":{"careai-dev-version":{"content":"${{ steps.buildnumber.outputs.build_number }}"}}}' \
          --fail
