name: Update version on PR merge

on: [ push ]

jobs:

  update_latest_version:
    runs-on: ubuntu-latest
    permissions:
      issues: write 
    steps:
      - name: Create new version using REST API
        run: |
          CURRENT_VERSION=$(curl --silent https://gist.githubusercontent.com/juanmjacobs/b20fe2465ce76776e0ae632095d9d7c7/raw?cache=${{ github.SHA }})
          echo CURRENT $CURRENT_VERSION
          NEW_VERSION=$((CURRENT_VERSION + 1))
          echo NEW $NEW_VERSION
          BODY={\"description\":\"v1.7.$NEW_VERSION sha: ${{ github.SHA }}\",\"files\":{\"careai-dev-version\":{\"content\":\"$NEW_VERSION\"}}}
          echo $BODY
          curl \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GIST_PAT }}" \
          https://api.github.com/gists/b20fe2465ce76776e0ae632095d9d7c7 \
          -d "$BODY" \
          --fail

